spring:
  datasource:
    url: jdbc:postgresql://localhost:15432/apiguard
    driver-class-name: org.postgresql.Driver
    username: apiguard
    password: apiguard1234
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  data:
    redis:
      host: localhost
      port: 6379
  mail:
    host: localhost
    port: 1025
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false
jwt:
  secret: 05da0a6607d4e09334c3f7f8ce1f361cb9b9dfac39143a2ab39da063185f57b39cc7ec746b23edf64b65e26823ac7d555507f826de68bd0277f0543c84155f9c

toss:
  payments:
    secret-key: test_sk_zXLkKEypNArWmo50nX3lmeaxYG5R
    client-key: test_ck_docs_Ovk5rk1EwkEbP0W43n07xlzm

security:
  whitelist:
    - /auth/** # 로그인, 토큰 재발급 등
    - /users/signup # 회원가입
    - /health
    - /error

    # 개발 환경
    - /swagger-ui/**
    - /v3/api-docs/**
