spring:
  datasource:
    url: jdbc:postgresql://localhost:15432/apiguard
    driver-class-name: org.postgresql.Driver
    username: apiguard
    password: apiguard1234
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  data:
    redis:
      host: localhost
      port: 6379
  mail:
    host: localhost
    port: 1025
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false
jwt:
  secret: **REMOVED-FROM-HISTORY**

toss:
  payments:
    secret-key: **REMOVED-FROM-HISTORY**
    client-key: **REMOVED-FROM-HISTORY**

security:
  whitelist:
    - /auth/** # 로그인, 토큰 재발급 등
    - /users/signup # 회원가입
    - /health
    - /error

    # 개발 환경
    - /swagger-ui/**
    - /v3/api-docs/**
  cors:
    allowed-origins:
      - http://localhost:3000
